### ISSUE TITLE
allow addition `rhgb quiet` to bootloader kernel args to be configurable

### ISSUE THREAD

**Issue by dustymabe** [dcantrell/pykickstart#153]
Can we please make the addition of [rhgb quiet](https://github.com/rhinstaller/pykickstart/blob/b7176cc61b8e9f15e06e672af0d1805708584420/pykickstart/commands/bootloader.py#L96-L99) to the kernel arguments be configurable? It would be preferable to not have to [hack up the bootloader configuration using sed](https://bugzilla.redhat.com/show_bug.cgi?id=510523) in order to disable this functionality.

**Comment by dustymabe** [comment]
should have opened this against anaconda. opened an issue there: https://github.com/rhinstaller/anaconda/issues/1079

**Comment by dcantrell** [comment]
Since the anaconda issue has been opened, I am closing this one.
