### ISSUE TITLE
Travis CI tests broken

### ISSUE THREAD

**Issue by M4rtinK** [dcantrell/pykickstart#257]
Looking at the errors & build hsitory:
https://travis-ci.org/dcantrell/pykickstart/builds

It seems to be related to changes in docs generation, (some) builds did pass CI runs before that.

**Comment by dcantrell** [comment]
Fixed.  Two problems:
1) sphinx-build-3 and sphinx-apidoc-3 did not exist, just call sphinx-build and sphinx-apidoc instead.
2) Python 3.7 required a different specification in .travis.yml
Fixed run:
https://travis-ci.org/dcantrell/pykickstart/builds/502672231
