### ISSUE TITLE
Upstream documentation is not updated

### ISSUE THREAD

**Issue by jkonecny12** [dcantrell/pykickstart#261]
The upstream documentation: https://pykickstart.readthedocs.io/ have %packages section which have arguments ``--nobase``, ``--resolvedeps`` and ``--ingoredeps`` as deprecated but these arguments are not just deprecated, they were removed. See the code: https://github.com/dcantrell/pykickstart/blob/master/pykickstart/sections.py#L672 .

We thought it is a docs generation issue but if I run `make docs` locally I see the removed messages there so it seems that the documentation is just not updated.

**Comment by M4rtinK** [comment]
Looks like the builds on Read the Docs are not being triggered by updates in git:
https://readthedocs.org/projects/pykickstart/builds/

The latest build seems to be ~5 months old - maybe that's when the repository has been moved and the URL on Read the Docs was not updated back then ?

In general it should likely be enough to go to the RTD project and switch the Git URL to the current one. For that thought I think you would need to ask @clumens to give you admin rights for the project, as he currently listed as the only admin:
https://readthedocs.org/projects/pykickstart/

**Comment by clumens** [comment]
I've changed the repo in the settings and triggered a new build.  Hopefully that'll work.  I can add whoever as a maintainer that wants to be.  Thanks for bringing this to my attention.

**Comment by clumens** [comment]
https://readthedocs.org/projects/pykickstart/builds/8781360/

**Comment by jkonecny12** [comment]
Looks correctly now. Thanks!
